<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
<!ELEMENT aeropuerto (nombre?, vuelo+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vuelo (diario, origen, destino, hora_salida, hora_llegada)>
<!ELEMENT diario (EMPTY)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ATTLIST vuelo codigo ID #REQUIRED>
<!ATTLIST vuelo estado (C|E|R) valor = "E" #REQUIRED>
]>

<aeropuerto>
    <nombre>Adolfo Su√°rez Madrid-Barajas</nombre>
    <vuelo codigo = "V22" estado = "R">
        <diario/>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
    </vuelo>
    <vuelo codigo = "V23" estado = "C">
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
    </vuelo>
</aeropuerto>