<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografía [
   <!ELEMENT geografia (paises, ciudades)>
<!ELEMENT paises (pais)*>
<!ELEMENT país (#PCDATA)>
<!ATTLIST país codpais ID #REQUIRED>
<!ELEMENT ciudades (ciudad)*>
<!ELEMENT ciudad (#PCDATA)>
<!ATTLIST ciudad pais IDREF #IMPLIED>
]>

<geografía>
    <paises>
        <país codpais="P1">Argentina</país>
        <país codpais="P2">Áustria</país>
        <país codpais="P3">Japón</país>
        <país codpais="P4">Noruega</país>
    </paises>
    <ciudades>
        <ciudad país="P1">Osaka</ciudad>
        <ciudad>Oslo</ciudad>
        <ciudad país="P2">Sevilla</ciudad>
        <ciudad país="P3">Tokio</ciudad>
        <ciudad país="P4">Viena</ciudad>
    </ciudades>
</geografía>
